#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.syngentaOrg.syngenta.com:
    image: hyperledger/fabric-ca:x86_64-1.0.3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.syngentaOrg.syngenta.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ed43de96fab8b12b6854e76e3098a54487b40a53a5acc9995db726791f7e6bd2_sk
      #- FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-tlsca-server-config/tlsca.syngentaOrg.syngenta.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-tlsca-server-config/94758aa1f9c2abdc36feca8f40f77f00a3e1c95d6a6e457cf70d815e6d75c6fb_sk
      - FABRIC_CA_SERVER_CA_NAME=ca.syngentaOrg.syngenta.com
      #- FABRIC_CA_SERVER_TLS_ENABLED=true      
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-tlsca-server-config/tlsca.syngentaOrg.syngenta.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-tlsca-server-config/94758aa1f9c2abdc36feca8f40f77f00a3e1c95d6a6e457cf70d815e6d75c6fb_sk
    ports:
      - "7054:7054"
    #command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.syngentaOrg.syngenta.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6fff3dd298c02d530b54de571e1b34dcd354c86f8c21de88956385673c4523c0_sk -b admin:adminpw' -d
    command: sh -c 'fabric-ca-server start -c /etc/hyperledger/fabric-ca-server/ca1-config.yaml -d'    
    volumes:
      - ./fabric-ca-server/ca1:/etc/hyperledger/fabric-ca-server
      - ./crypto-config/peerOrganizations/syngentaOrg.syngenta.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./crypto-config/peerOrganizations/syngentaOrg.syngenta.com/tlsca/:/etc/hyperledger/fabric-tlsca-server-config
    container_name: ca.syngentaOrg.syngenta.com

  ca.vendorOrg.syngenta.com:
    image: hyperledger/fabric-ca:x86_64-1.0.3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.vendorOrg.syngenta.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/87497d0fe5633efe9c8c4fce67bdc068ec8629e75897dc617c6e0e91db68fd14_sk
      - FABRIC_CA_SERVER_CA_NAME=ca.vendorOrg.syngenta.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-tlsca-server-config/tlsca.vendorOrg.syngenta.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-tlsca-server-config/0aeebe7667a5a80c1e1e25b6d99842f02cbce584523caca68d0f176efabe7493_sk
    ports:
      - "8054:7054"
    #command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.vendorOrg.syngenta.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0e92f45b8d4eb59cad258600f7cc74fc750d65b0d1ce7fe6b944f18012db798f_sk -b admin:adminpw' -d
    command: sh -c 'fabric-ca-server start -c /etc/hyperledger/fabric-ca-server/ca2-config.yaml -d'
    volumes:
      - ./fabric-ca-server/ca2:/etc/hyperledger/fabric-ca-server
      - ./crypto-config/peerOrganizations/vendorOrg.syngenta.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./crypto-config/peerOrganizations/vendorOrg.syngenta.com/tlsca/:/etc/hyperledger/fabric-tlsca-server-config
    container_name: ca.vendorOrg.syngenta.com
  
  ca.bankOrg.syngenta.com:
    image: hyperledger/fabric-ca:x86_64-1.0.3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bankOrg.syngenta.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8afdfcfeadcf0f8c9211679185796ab6af728cf954484966660a0a10c36605fa_sk
      - FABRIC_CA_SERVER_CA_NAME=ca.bankOrg.syngenta.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-tlsca-server-config/tlsca.bankOrg.syngenta.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-tlsca-server-config/f70704b9180d442d4c9cfe178582e86b782375ee7f22187e8e2697aa213ea928_sk
    ports:
      - "9054:7054"
    #command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bankOrg.syngenta.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/36ea237b4dec78da80f50ec7f9e0d5b93e7c91d807161fe389802643d4304ad1_sk -b admin:adminpw' -d
    command: sh -c 'fabric-ca-server start -c /etc/hyperledger/fabric-ca-server/ca3-config.yaml -d'
    volumes:
      - ./fabric-ca-server/ca3:/etc/hyperledger/fabric-ca-server
      - ./crypto-config/peerOrganizations/bankOrg.syngenta.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./crypto-config/peerOrganizations/bankOrg.syngenta.com/tlsca/:/etc/hyperledger/fabric-tlsca-server-config
    container_name: ca.bankOrg.syngenta.com
  
  orderer.syngenta.com:
    container_name: orderer.syngenta.com
    image: hyperledger/fabric-orderer:x86_64-1.0.3
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/syngentaGenesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      # - ORDERER_GENERAL_TLS_ENABLED=true
      # - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      # - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      # - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peersyngentaOrg/tls/ca.crt, /etc/hyperledger/crypto/peervendorOrg/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/syngenta.com/orderers/orderer.syngenta.com/:/etc/hyperledger/crypto/orderer
        - ./crypto-config/peerOrganizations/syngentaOrg.syngenta.com/peers/peer0.syngentaOrg.syngenta.com/:/etc/hyperledger/crypto/peersyngentaOrg
        - ./crypto-config/peerOrganizations/vendorOrg.syngenta.com/peers/peer0.vendorOrg.syngenta.com/:/etc/hyperledger/crypto/peervendorOrg

  peer0.syngentaOrg.syngenta.com:
    container_name: peer0.syngentaOrg.syngenta.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.syngentaOrg.syngenta.com
      - CORE_PEER_LOCALMSPID=SyngentaOrgMSP
      - CORE_PEER_ADDRESS=peer0.syngentaOrg.syngenta.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./crypto-config/peerOrganizations/syngentaOrg.syngenta.com/peers/peer0.syngentaOrg.syngenta.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.syngenta.com
  
  peer0.vendorOrg.syngenta.com:
    container_name: peer0.vendorOrg.syngenta.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.vendorOrg.syngenta.com
      - CORE_PEER_LOCALMSPID=VendorOrgMSP
      - CORE_PEER_ADDRESS=peer0.vendorOrg.syngenta.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./crypto-config/peerOrganizations/vendorOrg.syngenta.com/peers/peer0.vendorOrg.syngenta.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.syngenta.com
      
  peer0.bankOrg.syngenta.com:
    container_name: peer0.bankOrg.syngenta.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bankOrg.syngenta.com
      - CORE_PEER_LOCALMSPID=BankOrgMSP
      - CORE_PEER_ADDRESS=peer0.bankOrg.syngenta.com:7051
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ./crypto-config/peerOrganizations/bankOrg.syngenta.com/peers/peer0.bankOrg.syngenta.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.syngenta.com  

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.0.3
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.syngentaOrg.syngenta.com:7051
      - CORE_PEER_LOCALMSPID=SyngentaOrgMSP
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/syngentaOrg.syngenta.com/peers/peer0.syngentaOrg.syngenta.com/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/syngentaOrg.syngenta.com/peers/peer0.syngentaOrg.syngenta.com/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/syngentaOrg.syngenta.com/peers/peer0.syngentaOrg.syngenta.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/syngentaOrg.syngenta.com/users/Admin@syngentaOrg.syngenta.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh;'
    volumes:
        - /var/run/:/host/var/run/     
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts   
    depends_on:
      - orderer.syngenta.com
      - peer0.syngentaOrg.syngenta.com
      - peer0.vendorOrg.syngenta.com
      - peer0.bankOrg.syngenta.com